// All visible text of the public landing page, in English and Filipino.
// Record content (titles, summaries, news bodies) stays in its official English.

export type Lang = 'EN' | 'FIL';

const EN = {
  nav: {
    home: 'Home',
    legislation: 'Legislation',
    'sangguniang-bayan': 'The Sanggunian',
    'public-sessions': 'Sessions',
    resources: 'Resources',
    news: 'News',
    contact: 'Contact',
  },
  skipToMain: 'Skip to main content',
  republic: 'Republic of the Philippines',
  pst: 'Philippine Standard Time',
  staffLogin: 'Staff Login',
  systemName: 'Legislative Information Management System',
  logoAlt: 'LIMS logo',
  requestDocument: 'Request a Document',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',

  heroKicker: 'Official Legislative Portal',
  heroTitle: 'Transparent and Accessible Local Legislation',
  heroText:
    'Search ordinances and resolutions, follow session schedules, and request legislative documents through LIMS.',
  heroSlider: {
    carousel: 'Featured announcements',
    slideOf: (current: number, total: number) => `${current} of ${total}`,
    previous: 'Previous slide',
    next: 'Next slide',
    pause: 'Pause slideshow',
    play: 'Play slideshow',
    goTo: (slide: number) => `Go to slide ${slide}`,
  },
  slides: {
    welcome: { browse: 'Browse legislation' },
    hearing: {
      kicker: 'Public Hearing · October 7, 2026',
      title: 'Have Your Say on the Tricycle Franchising Ordinance',
      text: 'Operators, drivers, and commuters are invited to the Committee on Transportation hearing at 2:00 PM in the SB Session Hall.',
      read: 'Read announcement',
    },
    award: {
      kicker: 'Recognition · 2022–2025 Term',
      title: 'Regional Winner, Local Legislative Award',
      text: 'The municipal legislative council was recognized for the quality of its legislation, efficient procedures, and engagement with constituents.',
      read: 'Read more',
      meet: 'Meet the Sanggunian',
    },
    heritage: {
      kicker: 'Enacted Ordinance · Mun. Ord. No. 2026-005',
      title: 'Capas National Shrine Environs Now a Heritage Protection Zone',
      text: 'Signage, vending, and new construction within the buffer zone are now regulated to preserve the memorial of the Bataan Death March.',
      view: 'View ordinance',
    },
    register: {
      kicker: 'Stay Informed',
      title: 'Get Notified of New Ordinances and Public Hearings',
      text: 'Register with your email address to receive legislative updates from the SB Secretariat.',
      register: 'Register for updates',
      inquiry: 'Send an inquiry',
    },
  },
  searchPlaceholder: 'Search ordinances, resolutions, or record numbers',
  search: 'Search',
  clearSearch: 'Clear search',
  searchSuggestions: 'Search suggestions',
  noMatches: (query: string) => `No records match "${query}".`,
  noMatchesHint: 'Try a record number, title, or subject.',
  seeResults: (count: number) => (count === 1 ? 'See the result in Legislation' : `See all ${count} results in Legislation`),
  quickLinks: 'Quick links:',
  ordinances: 'Ordinances',
  resolutions: 'Resolutions',
  sessionCalendar: 'Session calendar',
  nextSession: 'Next session',
  time: 'Time',
  venue: 'Venue',
  viewAgenda: 'View Agenda',
  addToCalendar: 'Add to Calendar',
  sessionTypes: { Regular: 'Regular', Special: 'Special', 'Committee Hearing': 'Committee Hearing' } as Record<string, string>,

  services: 'Public Services',
  helpTitle: 'How can we help you?',
  tiles: {
    ordinances: { title: 'Ordinances', description: 'Search enacted and proposed ordinances' },
    resolutions: { title: 'Resolutions', description: 'Browse resolutions adopted by the SB' },
    calendar: { title: 'Session Calendar', description: 'Upcoming sessions and public hearings' },
    members: { title: 'Members & Committees', description: 'Composition of the Sanggunian' },
    request: { title: 'Request a Document', description: 'Copies of legislative records' },
    register: { title: 'Register for Updates', description: 'Get notified of new legislation' },
  },

  transparencyKicker: 'Transparency',
  overview: 'Legislative Records at a Glance',
  overviewText: 'Legislative records published on this portal, and sessions and committee hearings held this year.',
  stats: {
    ordinances: {
      label: 'Ordinances',
      description: 'Local laws on public safety, revenue, environment, and local governance.',
      action: 'Browse ordinances',
    },
    resolutions: {
      label: 'Resolutions',
      description: 'Formal expressions of the SB on policy direction, endorsements, and authorizations.',
      action: 'Browse resolutions',
    },
    sessions: {
      label: 'Sessions Held',
      description: 'Regular and special sessions this year where the SB deliberated on proposed measures.',
      action: 'View session calendar',
    },
    hearings: {
      label: 'Committee Hearings',
      description: 'Hearings and consultations this year before committee recommendations.',
      action: 'View hearings',
    },
  },

  process: {
    kicker: 'How It Works',
    title: 'How a Measure Becomes an Ordinance',
    text: 'Follow a proposed ordinance from filing to publication. Select a stage to see the measures now at that stage, or follow a specific measure.',
    play: 'Play',
    pause: 'Pause',
    replay: 'Replay',
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    measuresHere: (count: number) => `${count} measure${count === 1 ? '' : 's'} at this stage`,
    stageCount: (count: number) => `${count} measure${count === 1 ? '' : 's'}`,
    viewMeasures: 'View measures',
    followLabel: 'Follow a measure',
    followPlaceholder: 'Select a measure to track its progress',
    stopFollowing: 'Back to overview',
    currentStage: 'Current stage',
    filed: 'Filed',
    latestAction: 'Latest action',
    viewRecord: 'View record',
    legalBasis: 'Based on the Local Government Code of 1991 (RA 7160), Sections 54 and 59.',
    stages: {
      filing: {
        label: 'Filing',
        title: 'Filing of the Proposed Measure',
        description: 'A member or committee files the proposed ordinance with the Office of the Secretary to the Sanggunian, which assigns a number and includes it in the order of business.',
        points: ['Given a record number and tracking entry', 'Calendared for the next regular session'],
      },
      first: {
        label: 'First Reading',
        title: 'First Reading and Referral',
        description: 'The title of the measure is read in session, and the Presiding Officer refers it to the standing committee concerned.',
        points: ['Title read on the floor', 'Referred to the committee concerned'],
      },
      committee: {
        label: 'Committee',
        title: 'Committee Study and Public Hearing',
        description: 'The committee studies the measure, holds public hearings and consultations with affected sectors, and submits a committee report.',
        points: ['Public hearings and position papers', 'Committee report with recommendations'],
      },
      second: {
        label: 'Second Reading',
        title: 'Second Reading and Debate',
        description: 'The measure is debated in plenary session, where amendments may be proposed and voted on.',
        points: ['Period of debate and amendments', 'Approved on second reading'],
      },
      third: {
        label: 'Third Reading',
        title: 'Third Reading and Final Vote',
        description: 'The members present vote on the final version of the measure. No further amendments are allowed at this stage.',
        points: ['Nominal voting with a quorum present', 'Attested by the Presiding Officer and certified by the Secretary'],
      },
      approval: {
        label: 'Approval',
        title: 'Approval by the Municipal Mayor',
        description: 'The ordinance is transmitted to the Municipal Mayor, who may approve or veto it within ten days; if not acted upon, it is deemed approved.',
        points: ['A veto may be overridden by two-thirds of all members', 'Deemed approved if not acted upon within ten days'],
      },
      publication: {
        label: 'Publication',
        title: 'Posting, Publication, and Effectivity',
        description: 'The ordinance is posted at the municipal hall and in at least two other conspicuous places, and takes effect ten days after posting unless it states otherwise.',
        points: ['Ordinances with penal clauses are also published in a newspaper', 'Recorded in the Ordinance Archive'],
      },
    },
  },
  inquiryKicker: 'Public Inquiry',
  legislation: 'Legislation',
  legislationText:
    'Search ordinances, resolutions, incoming documents, and public resources. Open a record to view, download, or print a watermarked public copy.',
  tabsLabel: 'Record type',
  tabs: { all: 'All Records', ordinances: 'Ordinances', resolutions: 'Resolutions', incoming: 'Incoming Documents', resources: 'Resources' },
  all: 'All',
  recordTypes: { Legislation: 'Legislation', 'Incoming Document': 'Incoming Document', Resource: 'Resource' } as Record<string, string>,
  keywordPlaceholder: 'Keyword, record no., author, subject...',
  searchRecords: 'Search records',
  filters: {
    status: 'Status',
    category: 'Category',
    year: 'Year',
    type: 'Type',
    subject: 'Subject',
    referral: 'Referral',
    classification: 'Classification',
    actionTaken: 'Action taken',
    authorship: 'Authorship',
    sponsor: 'Sponsor',
    coAuthor: 'Co-author',
  },
  moreFilters: 'More filters',
  fewerFilters: 'Fewer filters',
  reset: 'Reset',
  recordsFound: (count: number) => `${count} record${count === 1 ? '' : 's'} found`,
  filtersApplied: (count: number) => `${count} filter${count === 1 ? '' : 's'} applied`,
  pagination: {
    showing: (start: number, end: number, total: number) => `Showing ${start}-${end} of ${total}`,
    previous: 'Previous',
    next: 'Next',
    page: (current: number, total: number) => `Page ${current} / ${total}`,
  },
  printList: 'Print list',
  exportCsv: 'Export CSV',
  listTitle: 'Public Records Listing',
  listFilters: 'Filters',
  listNone: 'None',
  listGenerated: 'Generated',
  table: { number: 'Record No.', title: 'Title', type: 'Type', date: 'Date', status: 'Status', actions: 'Actions', author: 'Author', referral: 'Referral' },
  actionsFor: (number: string) => `Actions for ${number}`,
  view: 'View',
  download: 'Download',
  print: 'Print',
  downloadPublicCopy: 'Download public copy',
  printPublicCopy: 'Print public copy',
  requestCertifiedCopy: 'Request certified copy',
  noRecords: 'No matching public records found.',
  clearFilters: 'Clear filters',
  nothingToExport: 'There are no records to export. Clear the filters and try again.',
  popupBlocked: 'Allow pop-ups for this site to print.',
  downloadFailed: 'The download could not be started.',

  sbKicker: 'Legislative Body',
  sb: 'Members and Committees',
  sbText:
    'The legislative body of the Municipality of Capas, presided over by the Municipal Vice Mayor. It enacts ordinances, adopts resolutions, and appropriates funds for the general welfare of the municipality and its inhabitants.',
  councilors: 'Municipal Councilors',
  exOfficio: 'Ex-officio Members',
  standingCommittees: 'Standing Committees',
  composition: {
    regularMembers: 'Regular members',
    regularSummary: (count: number) => `${count} councilors · elected at large`,
    exOfficioMembers: 'Ex-officio members',
    presidingOfficer: 'Presiding Officer',
    presides: 'Presides over sessions',
    chair: 'Chair',
    committees: (count: number) => `${count} committees`,
    roles: { 'SB Member': 'SB Member', 'Ex-officio SB Member': 'Ex-officio SB Member' } as Record<string, string>,
  },
  compositionTitle: 'Member Composition',
  compositionText: (count: number) => `${count} members · select a member to see their committee assignments`,
  chair: 'Chair',
  chairLegend: 'chairs at least one committee',
  committeesHint: 'Select a committee to see the measures referred to it.',
  committeeAssignments: 'Committee assignments',
  roles: { Chair: 'Chair', 'Vice Chair': 'Vice Chair', Member: 'Member' } as Record<string, string>,
  presidingNote: 'The Municipal Vice Mayor presides over sessions and does not sit in standing committees.',
  noAssignments: 'No committee assignments.',

  scheduleKicker: 'Schedule',
  sessions: 'Sessions and Hearings',
  sessionsText: (hall: string) =>
    `Sessions are open to the public and held at the ${hall}. View the order of business, add a session to your calendar, or print the agenda.`,
  agenda: 'Agenda',
  addToCalendarFor: (title: string) => `Add ${title} to calendar`,
  recentTitle: 'Recently Approved Measures',
  recentText: 'Ordinances and resolutions approved by the SB.',
  viewAllLegislation: 'View all legislation',

  downloadsKicker: 'Downloads',
  resources: 'Resources and Forms',
  resourcesText: 'Guides, archives, and forms for citizens and organizations. Downloaded and printed copies carry a public-copy watermark.',
  resourceCards: {
    'res-1': { title: 'Citizen Guidebook', description: 'How to participate in public hearings and legislative consultations.' },
    'res-3': { title: 'Ordinance Archive', description: 'Index of enacted municipal ordinances by number, title, and year.' },
    'res-4': { title: 'Session Minutes', description: 'Approved minutes of regular and special sessions of the SB.' },
    'res-2': { title: 'Accreditation Form', description: 'Request form for accreditation of civil society organizations.' },
  } as Record<string, { title: string; description: string }>,
  registerTitle: 'Register for Legislative Updates',
  registerText: 'Receive notices of new ordinances, resolutions, and public hearings.',
  fullName: 'Full name',
  emailAddress: 'Email address',
  subscribeLabel: 'Subscribe to ordinance and resolution updates',
  register: 'Register',
  howWeUseData: 'How we use your data',
  accTitle: 'Check Accreditation Status',
  accText: "Enter the reference number of your organization's accreditation request.",
  accPlaceholder: 'e.g. ACC-2026-005',
  accLabel: 'Accreditation reference number',
  check: 'Check',
  downloadAccForm: 'Download accreditation form',
  requestADocument: 'Request a document',

  newsKicker: 'Updates',
  news: 'News and Announcements',
  newsText: 'Recent actions, notices, and announcements posted on LIMS.',
  readMore: 'Read more',
  viewRelatedDocument: 'View related document',

  contactKicker: 'Get in Touch',
  contactTitle: 'Contact the SB Office',
  contactText: 'Visit, call, or write to the Office of the Secretary to the Sanggunian for inquiries, document requests, and position papers.',
  officeAddress: 'Office address',
  officeName: 'Legislative Office',
  officeHours: 'Office hours',
  officeHoursValue: 'Monday to Friday, 8:00 AM – 5:00 PM (except holidays)',
  email: 'Email',
  viber: 'Viber',
  website: 'Website',
  municipalWebsite: 'Municipality of Capas website',
  mapTitle: 'Map of the Capas Municipal Hall',
  getDirections: 'Get directions',
  inquiryTitle: 'Send an Inquiry',
  inquiryText: 'Questions about a measure, session, or document? The Secretariat replies by email within three working days.',
  subject: 'Subject',
  message: 'Your message',
  sendInquiry: 'Send inquiry',
  inquiryReceived: (reference: string, email: string) =>
    `Inquiry received. Your reference number is ${reference}; the Secretariat will reply to ${email}.`,

  transparencyTitle: 'Transparency and Accountability',
  transparencyDescriptions: [
    'Budget, procurement, and performance disclosures',
    'Service standards of the Municipality of Capas',
    'File an FOI request online',
    'DILG Full Disclosure Policy Portal',
  ],

  publicDomain: 'All content is in the public domain unless otherwise stated.',
  aboutGovph: 'About GOVPH',
  aboutGovphText: 'Learn more about the Philippine government, its structure, how government works, and the people behind it.',
  governmentLinks: 'Government Links',
  rightsReserved: 'All rights reserved.',
  privacy: 'Privacy Notice',
  terms: 'Terms of Use',
  accessibility: 'Accessibility',
  backToTop: 'Back to top',

  loginText: 'For authorized LIMS personnel.',
  username: 'Username',
  password: 'Password',
  enterUsername: 'Enter username',
  enterPassword: 'Enter password',
  rememberMe: 'Remember me',
  signIn: 'Sign in',
  demoAccess: 'Demo access:',
  otherRoles: 'Other roles:',
  samePassword: '(same password)',
  loginMissing: 'Please enter your username and password.',
  loginInvalid: 'Invalid username or password. Please try again.',
  loginDeactivated: 'This account is deactivated. Contact the SB Secretariat administrator.',
  accountDeactivated: 'This account is deactivated.',
  signInFailed: 'Sign-in failed',
  signedIn: 'Signed in',
  welcomeAs: (name: string, role: string) => `Welcome, ${name}. You are signed in as ${role}.`,
  loginDestination: 'Sign in to',
  staffPortal: 'Staff Portal',
  eSession: 'E-Session',
  eSessionLoginText: 'Join or conduct a live e-session of the Sanggunian.',
  eSessionSignIn: 'Sign in to E-Session',
  eSessionMembers: 'Members:',
  eSessionStaff: 'Staff:',
  eSessionNoSessions: (role: string) => `The ${role} role does not take part in sessions. Sign in to the Staff Portal instead.`,
  memberUseESession: 'Members of the Sanggunian sign in to E-Session or LIMS Mobile, not the Staff Portal.',
  eSessionWelcome: (name: string) => `Welcome, ${name}. Opening E-Session…`,

  viewerTitle: 'Public Document Viewer',
  viewerText: 'View, download, or print a watermarked public copy.',
  fields: {
    date: 'Date',
    category: 'Category',
    subject: 'Subject',
    referral: 'Referral',
    classification: 'Classification',
    actionTaken: 'Action taken',
    author: 'Author',
    coAuthor: 'Co-author',
  },
  orderOfBusiness: 'Order of Business',
  printAgenda: 'Print agenda',

  requestText: 'Request a certified copy of a legislative record from the Office of the Secretary to the Sanggunian.',
  requestRecordPlaceholder: 'Record number or title (e.g. Mun. Ord. No. 2026-005)',
  requestRecordLabel: 'Document requested',
  purpose: 'Purpose',
  purposes: {
    'Personal reference': 'Personal reference',
    'Research / Academic': 'Research / Academic',
    'Legal proceedings': 'Legal proceedings',
    'Business compliance': 'Business compliance',
    Other: 'Other',
  } as Record<string, string>,
  consentBefore: 'By submitting, you agree to the processing of your personal data under the',
  submitRequest: 'Submit request',
  requestReceivedTitle: 'Request received',
  requestReceivedText: (reference: string, email: string) =>
    `Your reference number is ${reference}. A confirmation will be sent to ${email}. Please present this reference number when claiming your document at the SB Office.`,
  done: 'Done',
  cancel: 'Cancel',

  // Form feedback
  needNameEmail: 'Please provide your full name and email address.',
  invalidEmail: 'Please enter a valid email address.',
  notValidEmail: (email: string) => `${email} is not a valid email address.`,
  registrationNotSaved: 'Registration not saved',
  confirmRegistrationTitle: 'Submit your registration?',
  confirmRegistrationSubscribed: (name: string, email: string) => `${name} will be registered with ${email} and subscribed to legislative updates.`,
  confirmRegistration: (name: string, email: string) => `${name} will be registered with ${email}.`,
  registrationSaved: 'Registration saved',
  registrationSubscribed: 'Registration saved. You are now subscribed to legislative updates.',
  registrationNoUpdates: 'Registration saved. You may enable updates anytime.',
  enterReference: 'Please enter a reference number.',
  lookupFailed: 'Lookup failed',
  accFound: 'Accreditation found',
  accNotFoundTitle: 'Accreditation not found',
  accNotFound: (key: string) => `No accreditation request found for ${key}.`,
  requestIncomplete: 'Please complete your name, email address, and the document requested.',
  requestNotSubmitted: 'Request not submitted',
  confirmRequestTitle: 'Submit this document request?',
  confirmRequest: (record: string, email: string) => `A request for "${record}" will be sent to the SB Secretariat. Updates will go to ${email}.`,
  requestSubmitted: 'Request submitted',
  yourReference: (reference: string) => `Your reference number is ${reference}.`,
  inquiryIncomplete: 'Please complete your name, email address, and message.',
  inquiryNotSent: 'Inquiry not sent',
  confirmInquiryTitle: 'Send this inquiry?',
  confirmInquiry: (email: string) => `Your inquiry will be sent to the SB Secretariat. The reply will go to ${email}.`,
  inquirySent: 'Inquiry sent',

  policies: {
    privacy: [
      'LIMS collects only the personal information needed to process public registrations, inquiries, and requests for legislative documents, in accordance with the Data Privacy Act of 2012 (RA 10173).',
      'Information is used solely for the stated purpose, kept only as long as necessary, and protected against unauthorized access. You may request access to, correction of, or deletion of your data through the Office of the Secretary to the Sanggunian at {email}.',
    ],
    terms: [
      'Documents on this portal are provided for public information. Downloaded and printed copies are marked “Public Copy” and are not certified true copies. Certified copies may be requested from the Office of the Secretary to the Sanggunian.',
    ],
    accessibility: [
      'This portal is designed to work on phones, tablets, and desktop computers, supports keyboard navigation, and uses readable text and color contrast. Report accessibility issues to {email}.',
    ],
  },
};

export type LandingCopy = typeof EN;

const FIL: LandingCopy = {
  nav: {
    home: 'Tahanan',
    legislation: 'Lehislasyon',
    'sangguniang-bayan': 'Sanggunian',
    'public-sessions': 'Sesyon',
    resources: 'Dokumento',
    news: 'Balita',
    contact: 'Ugnayan',
  },
  skipToMain: 'Lumaktaw sa pangunahing nilalaman',
  republic: 'Republika ng Pilipinas',
  pst: 'Oras sa Pilipinas',
  staffLogin: 'Pag-login ng Kawani',
  systemName: 'Sistema ng Pamamahala ng Impormasyong Pambatasan',
  logoAlt: 'Logo ng LIMS',
  requestDocument: 'Humiling ng Dokumento',
  openMenu: 'Buksan ang menu',
  closeMenu: 'Isara ang menu',

  heroKicker: 'Opisyal na Portal ng Lehislasyon',
  heroTitle: 'Bukas at Abot-kayang Lokal na Lehislasyon',
  heroText:
    'Maghanap ng mga ordinansa at resolusyon, subaybayan ang iskedyul ng mga sesyon, at humiling ng mga dokumento sa pamamagitan ng LIMS.',
  heroSlider: {
    carousel: 'Mga tampok na anunsyo',
    slideOf: (current: number, total: number) => `${current} sa ${total}`,
    previous: 'Nakaraang slide',
    next: 'Susunod na slide',
    pause: 'Ihinto ang slideshow',
    play: 'Ituloy ang slideshow',
    goTo: (slide: number) => `Pumunta sa slide ${slide}`,
  },
  slides: {
    welcome: { browse: 'Tingnan ang lehislasyon' },
    hearing: {
      kicker: 'Pampublikong Pagdinig · Oktubre 7, 2026',
      title: 'Makilahok sa Pagdinig sa Ordinansa sa Prangkisa ng Traysikel',
      text: 'Inaanyayahan ang mga operator, drayber, at pasahero sa pagdinig ng Komite sa Transportasyon, 2:00 PM sa SB Session Hall.',
      read: 'Basahin ang anunsyo',
    },
    award: {
      kicker: 'Pagkilala · Termino 2022–2025',
      title: 'Regional Winner, Local Legislative Award',
      text: 'Kinilala ang lehislatibong kapulungan ng bayan sa kalidad ng lehislasyon, mahusay na proseso, at pakikipag-ugnayan sa mamamayan.',
      read: 'Basahin pa',
      meet: 'Kilalanin ang Sanggunian',
    },
    heritage: {
      kicker: 'Pinagtibay na Ordinansa · Mun. Ord. No. 2026-005',
      title: 'Paligid ng Capas National Shrine, Heritage Protection Zone na',
      text: 'Kinokontrol na ang mga karatula, pagtitinda, at bagong konstruksyon sa buffer zone upang mapangalagaan ang alaala ng Bataan Death March.',
      view: 'Tingnan ang ordinansa',
    },
    register: {
      kicker: 'Manatiling Updated',
      title: 'Maabisuhan sa mga Bagong Ordinansa at Pagdinig',
      text: 'Magparehistro gamit ang iyong email upang makatanggap ng mga update mula sa SB Secretariat.',
      register: 'Magparehistro',
      inquiry: 'Magpadala ng katanungan',
    },
  },
  searchPlaceholder: 'Maghanap ng ordinansa, resolusyon, o numero ng rekord',
  search: 'Hanapin',
  clearSearch: 'Burahin ang hinahanap',
  searchSuggestions: 'Mga mungkahi sa paghahanap',
  noMatches: (query: string) => `Walang rekord na tumutugma sa "${query}".`,
  noMatchesHint: 'Subukan ang numero, pamagat, o paksa ng rekord.',
  seeResults: (count: number) => (count === 1 ? 'Tingnan ang resulta sa Lehislasyon' : `Tingnan ang lahat ng ${count} resulta sa Lehislasyon`),
  quickLinks: 'Mabilisang link:',
  ordinances: 'Mga Ordinansa',
  resolutions: 'Mga Resolusyon',
  sessionCalendar: 'Kalendaryo ng sesyon',
  nextSession: 'Susunod na sesyon',
  time: 'Oras',
  venue: 'Lugar',
  viewAgenda: 'Tingnan ang Agenda',
  addToCalendar: 'Idagdag sa Kalendaryo',
  sessionTypes: { Regular: 'Regular', Special: 'Espesyal', 'Committee Hearing': 'Pagdinig ng Komite' },

  services: 'Mga Serbisyong Pampubliko',
  helpTitle: 'Paano kami makatutulong?',
  tiles: {
    ordinances: { title: 'Mga Ordinansa', description: 'Maghanap ng mga pinagtibay at iminungkahing ordinansa' },
    resolutions: { title: 'Mga Resolusyon', description: 'Tingnan ang mga resolusyong pinagtibay ng SB' },
    calendar: { title: 'Kalendaryo ng Sesyon', description: 'Mga darating na sesyon at pampublikong pagdinig' },
    members: { title: 'Mga Miyembro at Komite', description: 'Komposisyon ng Sanggunian' },
    request: { title: 'Humiling ng Dokumento', description: 'Mga kopya ng rekord pambatasan' },
    register: { title: 'Magparehistro para sa Update', description: 'Maabisuhan sa mga bagong lehislasyon' },
  },

  transparencyKicker: 'Bukas na Pamamahala',
  overview: 'Buod ng mga Rekord',
  overviewText: 'Mga rekord pambatasan na nakalathala sa portal na ito, at mga sesyon at pagdinig ng komite ngayong taon.',
  stats: {
    ordinances: {
      label: 'Mga Ordinansa',
      description: 'Mga lokal na batas sa kaligtasan ng publiko, kita, kapaligiran, at lokal na pamamahala.',
      action: 'Tingnan ang mga ordinansa',
    },
    resolutions: {
      label: 'Mga Resolusyon',
      description: 'Pormal na pahayag ng SB sa direksyon ng patakaran, pag-endorso, at pagbibigay-awtoridad.',
      action: 'Tingnan ang mga resolusyon',
    },
    sessions: {
      label: 'Mga Sesyong Naganap',
      description: 'Mga regular at espesyal na sesyon ngayong taon kung saan tinalakay ng SB ang mga panukala.',
      action: 'Tingnan ang kalendaryo',
    },
    hearings: {
      label: 'Mga Pagdinig ng Komite',
      description: 'Mga pagdinig at konsultasyon ngayong taon bago ang rekomendasyon ng komite.',
      action: 'Tingnan ang mga pagdinig',
    },
  },

  process: {
    kicker: 'Paano Ito Gumagana',
    title: 'Paano Nagiging Ordinansa ang Isang Panukala',
    text: 'Sundan ang isang panukalang ordinansa mula paghahain hanggang paglalathala. Pumili ng yugto upang makita ang mga panukalang nasa yugtong iyon, o sundan ang isang partikular na panukala.',
    play: 'I-play',
    pause: 'Ihinto',
    replay: 'Ulitin',
    stepOf: (step: number, total: number) => `Hakbang ${step} sa ${total}`,
    measuresHere: (count: number) => `${count} panukala ang nasa yugtong ito`,
    stageCount: (count: number) => `${count} panukala`,
    viewMeasures: 'Tingnan ang mga panukala',
    followLabel: 'Sundan ang isang panukala',
    followPlaceholder: 'Pumili ng panukalang susubaybayan',
    stopFollowing: 'Bumalik sa buod',
    currentStage: 'Kasalukuyang yugto',
    filed: 'Inihain',
    latestAction: 'Pinakahuling aksyon',
    viewRecord: 'Tingnan ang rekord',
    legalBasis: 'Batay sa Local Government Code of 1991 (RA 7160), Seksyon 54 at 59.',
    stages: {
      filing: {
        label: 'Paghahain',
        title: 'Paghahain ng Panukala',
        description: 'Inihahain ng miyembro o komite ang panukalang ordinansa sa Tanggapan ng Kalihim ng Sanggunian, na nagbibigay ng numero at isinasama ito sa kaayusan ng gawain.',
        points: ['Binibigyan ng numero at tracking entry', 'Isinasama sa susunod na regular na sesyon'],
      },
      first: {
        label: 'Unang Pagbasa',
        title: 'Unang Pagbasa at Pagsangguni',
        description: 'Binabasa sa sesyon ang pamagat ng panukala, at isinasangguni ito ng Namumunong Opisyal sa kinauukulang pirmihang komite.',
        points: ['Binabasa ang pamagat sa sesyon', 'Isinasangguni sa kinauukulang komite'],
      },
      committee: {
        label: 'Komite',
        title: 'Pag-aaral ng Komite at Pampublikong Pagdinig',
        description: 'Pinag-aaralan ng komite ang panukala, nagsasagawa ng pampublikong pagdinig at konsultasyon sa mga apektadong sektor, at nagsusumite ng ulat ng komite.',
        points: ['Pampublikong pagdinig at position paper', 'Ulat ng komite at mga rekomendasyon'],
      },
      second: {
        label: 'Ikalawang Pagbasa',
        title: 'Ikalawang Pagbasa at Debate',
        description: 'Pinagdedebatehan ang panukala sa sesyon, kung saan maaaring magmungkahi at bumoto sa mga susog.',
        points: ['Panahon ng debate at pagsusog', 'Inaprubahan sa ikalawang pagbasa'],
      },
      third: {
        label: 'Ikatlong Pagbasa',
        title: 'Ikatlong Pagbasa at Huling Botohan',
        description: 'Binoboto ng mga miyembrong naroroon ang huling bersyon ng panukala. Wala nang susog na pinapayagan sa yugtong ito.',
        points: ['Nominal na botohan na may quorum', 'Pinatutunayan ng Namumunong Opisyal at ng Kalihim'],
      },
      approval: {
        label: 'Pag-apruba',
        title: 'Pag-apruba ng Punong-Bayan',
        description: 'Ipinapadala ang ordinansa sa Punong-Bayan, na maaaring mag-apruba o mag-veto sa loob ng sampung araw; kung walang aksyon, itinuturing itong aprubado.',
        points: ['Maaaring baligtarin ang veto sa boto ng dalawang-katlo ng lahat ng miyembro', 'Aprubado kung walang aksyon sa loob ng sampung araw'],
      },
      publication: {
        label: 'Paglalathala',
        title: 'Pagpapaskil, Paglalathala, at Pagkabisa',
        description: 'Ipinapaskil ang ordinansa sa munisipyo at sa hindi bababa sa dalawa pang kapansin-pansing lugar, at nagkakabisa sampung araw matapos ipaskil maliban kung iba ang nakasaad.',
        points: ['Inilalathala rin sa pahayagan ang mga ordinansang may parusa', 'Itinatala sa Archive ng Ordinansa'],
      },
    },
  },
  inquiryKicker: 'Pampublikong Pagtatanong',
  legislation: 'Lehislasyon',
  legislationText:
    'Maghanap ng mga ordinansa, resolusyon, papasok na dokumento, at pampublikong sanggunian. Buksan ang rekord upang tingnan, i-download, o i-print ang pampublikong kopya na may watermark.',
  tabsLabel: 'Uri ng rekord',
  tabs: { all: 'Lahat ng Rekord', ordinances: 'Mga Ordinansa', resolutions: 'Mga Resolusyon', incoming: 'Mga Papasok na Dokumento', resources: 'Mga Dokumento' },
  all: 'Lahat',
  recordTypes: { Legislation: 'Lehislasyon', 'Incoming Document': 'Papasok na Dokumento', Resource: 'Dokumento' },
  keywordPlaceholder: 'Keyword, numero ng rekord, may-akda, paksa...',
  searchRecords: 'Maghanap ng rekord',
  filters: {
    status: 'Katayuan',
    category: 'Kategorya',
    year: 'Taon',
    type: 'Uri',
    subject: 'Paksa',
    referral: 'Komiteng pinagsangguni',
    classification: 'Klasipikasyon',
    actionTaken: 'Aksyong ginawa',
    authorship: 'Pagiging may-akda',
    sponsor: 'Isponsor',
    coAuthor: 'Kapwa may-akda',
  },
  moreFilters: 'Dagdag na filter',
  fewerFilters: 'Bawasan ang filter',
  reset: 'I-reset',
  recordsFound: (count: number) => `${count} rekord ang natagpuan`,
  filtersApplied: (count: number) => `${count} filter ang nakalapat`,
  pagination: {
    showing: (start: number, end: number, total: number) => `Ipinapakita ang ${start}-${end} sa ${total}`,
    previous: 'Nakaraan',
    next: 'Susunod',
    page: (current: number, total: number) => `Pahina ${current} / ${total}`,
  },
  printList: 'I-print ang listahan',
  exportCsv: 'I-export (CSV)',
  listTitle: 'Listahan ng mga Pampublikong Rekord',
  listFilters: 'Mga filter',
  listNone: 'Wala',
  listGenerated: 'Ginawa noong',
  table: { number: 'Blg. ng Rekord', title: 'Pamagat', type: 'Uri', date: 'Petsa', status: 'Katayuan', actions: 'Mga aksyon', author: 'May-akda', referral: 'Komiteng pinagsangguni' },
  actionsFor: (number: string) => `Mga aksyon para sa ${number}`,
  view: 'Tingnan',
  download: 'I-download',
  print: 'I-print',
  downloadPublicCopy: 'I-download ang pampublikong kopya',
  printPublicCopy: 'I-print ang pampublikong kopya',
  requestCertifiedCopy: 'Humiling ng sertipikadong kopya',
  noRecords: 'Walang tugmang pampublikong rekord.',
  clearFilters: 'Alisin ang mga filter',
  nothingToExport: 'Walang rekord na mai-e-export. Alisin ang mga filter at subukang muli.',
  popupBlocked: 'Payagan ang mga pop-up sa site na ito upang makapag-print.',
  downloadFailed: 'Hindi masimulan ang pag-download.',

  sbKicker: 'Lehislatibong Kapulungan',
  sb: 'Mga Kasapi at Komite',
  sbText:
    'Ang lehislatibong kapulungan ng Bayan ng Capas, na pinamumunuan ng Pangalawang Punong-Bayan. Ito ay nagpapatibay ng mga ordinansa at resolusyon at naglalaan ng pondo para sa pangkalahatang kapakanan ng bayan at ng mga mamamayan nito.',
  councilors: 'Mga Konsehal ng Bayan',
  exOfficio: 'Mga Ex-officio na Miyembro',
  standingCommittees: 'Mga Pirmihang Komite',
  composition: {
    regularMembers: 'Mga regular na miyembro',
    regularSummary: (count: number) => `${count} konsehal · inihalal ng buong bayan`,
    exOfficioMembers: 'Mga ex-officio na miyembro',
    presidingOfficer: 'Namumunong Opisyal',
    presides: 'Namumuno sa mga sesyon',
    chair: 'Tagapangulo',
    committees: (count: number) => `${count} komite`,
    roles: { 'SB Member': 'Miyembro ng SB', 'Ex-officio SB Member': 'Ex-officio na Miyembro ng SB' },
  },
  compositionTitle: 'Komposisyon ng mga Kasapi',
  compositionText: (count: number) => `${count} miyembro · pumili ng miyembro upang makita ang kanilang mga komite`,
  chair: 'Tagapangulo',
  chairLegend: 'namumuno sa kahit isang komite',
  committeesHint: 'Pumili ng komite upang makita ang mga panukalang isinangguni rito.',
  committeeAssignments: 'Mga komiteng kinabibilangan',
  roles: { Chair: 'Tagapangulo', 'Vice Chair': 'Pangalawang Tagapangulo', Member: 'Miyembro' },
  presidingNote: 'Ang Pangalawang Punong-Bayan ang namumuno sa mga sesyon at hindi kabilang sa mga pirmihang komite.',
  noAssignments: 'Walang komiteng kinabibilangan.',

  scheduleKicker: 'Iskedyul',
  sessions: 'Mga Sesyon at Pagdinig',
  sessionsText: (hall: string) =>
    `Bukas sa publiko ang mga sesyon na ginaganap sa ${hall}. Tingnan ang kaayusan ng gawain, idagdag ang sesyon sa iyong kalendaryo, o i-print ang agenda.`,
  agenda: 'Agenda',
  addToCalendarFor: (title: string) => `Idagdag ang ${title} sa kalendaryo`,
  recentTitle: 'Mga Bagong Aprubadong Panukala',
  recentText: 'Mga ordinansa at resolusyong inaprubahan ng SB.',
  viewAllLegislation: 'Tingnan ang lahat ng lehislasyon',

  downloadsKicker: 'Mga Download',
  resources: 'Mga Dokumento at Porma',
  resourcesText: 'Mga gabay, archive, at porma para sa mamamayan at mga organisasyon. May watermark na pampublikong kopya ang mga na-download at na-print.',
  resourceCards: {
    'res-1': { title: 'Gabay ng Mamamayan', description: 'Paano makilahok sa mga pampublikong pagdinig at konsultasyong pambatasan.' },
    'res-3': { title: 'Archive ng Ordinansa', description: 'Talaan ng mga pinagtibay na ordinansa ayon sa numero, pamagat, at taon.' },
    'res-4': { title: 'Katitikan ng Sesyon', description: 'Mga aprubadong katitikan ng regular at espesyal na sesyon ng SB.' },
    'res-2': { title: 'Porma ng Akreditasyon', description: 'Porma ng paghiling ng akreditasyon para sa mga civil society organization.' },
  },
  registerTitle: 'Magparehistro para sa mga Update sa Lehislasyon',
  registerText: 'Makatanggap ng abiso sa mga bagong ordinansa, resolusyon, at pampublikong pagdinig.',
  fullName: 'Buong pangalan',
  emailAddress: 'Email address',
  subscribeLabel: 'Mag-subscribe sa mga update ng ordinansa at resolusyon',
  register: 'Magparehistro',
  howWeUseData: 'Paano namin ginagamit ang iyong datos',
  accTitle: 'Alamin ang Katayuan ng Akreditasyon',
  accText: 'Ilagay ang reference number ng kahilingan sa akreditasyon ng iyong organisasyon.',
  accPlaceholder: 'hal. ACC-2026-005',
  accLabel: 'Reference number ng akreditasyon',
  check: 'Suriin',
  downloadAccForm: 'I-download ang porma ng akreditasyon',
  requestADocument: 'Humiling ng dokumento',

  newsKicker: 'Mga Update',
  news: 'Balita at Anunsyo',
  newsText: 'Mga kamakailang aksyon, abiso, at anunsyo na nakapaskil sa LIMS.',
  readMore: 'Basahin pa',
  viewRelatedDocument: 'Tingnan ang kaugnay na dokumento',

  contactKicker: 'Makipag-ugnayan',
  contactTitle: 'Makipag-ugnayan sa Tanggapan ng SB',
  contactText: 'Bumisita, tumawag, o sumulat sa Tanggapan ng Kalihim ng Sanggunian para sa mga katanungan, paghiling ng dokumento, at position paper.',
  officeAddress: 'Address ng tanggapan',
  officeName: 'Tanggapang Pambatasan',
  officeHours: 'Oras ng tanggapan',
  officeHoursValue: 'Lunes hanggang Biyernes, 8:00 AM – 5:00 PM (maliban sa pista opisyal)',
  email: 'Email',
  viber: 'Viber',
  website: 'Website',
  municipalWebsite: 'Website ng Bayan ng Capas',
  mapTitle: 'Mapa ng Munisipyo ng Capas',
  getDirections: 'Kumuha ng direksyon',
  inquiryTitle: 'Magpadala ng Katanungan',
  inquiryText: 'May tanong tungkol sa panukala, sesyon, o dokumento? Sasagot ang Secretariat sa email sa loob ng tatlong araw ng trabaho.',
  subject: 'Paksa',
  message: 'Ang iyong mensahe',
  sendInquiry: 'Ipadala',
  inquiryReceived: (reference: string, email: string) =>
    `Natanggap ang iyong katanungan. Ang iyong reference number ay ${reference}; sasagot ang Secretariat sa ${email}.`,

  transparencyTitle: 'Transparency at Pananagutan',
  transparencyDescriptions: [
    'Mga pagsisiwalat sa badyet, procurement, at pagganap',
    'Pamantayan ng serbisyo ng Bayan ng Capas',
    'Maghain ng FOI request online',
    'Portal ng Full Disclosure Policy ng DILG',
  ],

  publicDomain: 'Ang lahat ng nilalaman ay pampubliko maliban kung iba ang nakasaad.',
  aboutGovph: 'Tungkol sa GOVPH',
  aboutGovphText: 'Alamin ang tungkol sa pamahalaan ng Pilipinas, ang istruktura nito, kung paano ito gumagana, at ang mga taong nasa likod nito.',
  governmentLinks: 'Mga Link ng Pamahalaan',
  rightsReserved: 'Nakalaan ang lahat ng karapatan.',
  privacy: 'Abiso sa Privacy',
  terms: 'Mga Tuntunin ng Paggamit',
  accessibility: 'Accessibility',
  backToTop: 'Bumalik sa itaas',

  loginText: 'Para sa mga awtorisadong kawani ng LIMS.',
  username: 'Username',
  password: 'Password',
  enterUsername: 'Ilagay ang username',
  enterPassword: 'Ilagay ang password',
  rememberMe: 'Tandaan ako',
  signIn: 'Mag-sign in',
  demoAccess: 'Demo access:',
  otherRoles: 'Iba pang tungkulin:',
  samePassword: '(parehong password)',
  loginMissing: 'Pakilagay ang iyong username at password.',
  loginInvalid: 'Mali ang username o password. Pakisubukang muli.',
  loginDeactivated: 'Naka-deactivate ang account na ito. Makipag-ugnayan sa administrator ng SB Secretariat.',
  accountDeactivated: 'Naka-deactivate ang account na ito.',
  signInFailed: 'Hindi nakapag-sign in',
  signedIn: 'Naka-sign in',
  welcomeAs: (name: string, role: string) => `Maligayang pagdating, ${name}. Naka-sign in ka bilang ${role}.`,
  loginDestination: 'Mag-sign in sa',
  staffPortal: 'Staff Portal',
  eSession: 'E-Session',
  eSessionLoginText: 'Sumali o magsagawa ng live na e-session ng Sanggunian.',
  eSessionSignIn: 'Mag-sign in sa E-Session',
  eSessionMembers: 'Mga kasapi:',
  eSessionStaff: 'Kawani:',
  eSessionNoSessions: (role: string) => `Ang tungkuling ${role} ay hindi kasali sa mga sesyon. Gamitin na lang ang Staff Portal.`,
  memberUseESession: 'Ang mga miyembro ng Sanggunian ay nagsa-sign in sa E-Session o LIMS Mobile, hindi sa Staff Portal.',
  eSessionWelcome: (name: string) => `Maligayang pagdating, ${name}. Binubuksan ang E-Session…`,

  viewerTitle: 'Tagatingin ng Pampublikong Dokumento',
  viewerText: 'Tingnan, i-download, o i-print ang pampublikong kopya na may watermark.',
  fields: {
    date: 'Petsa',
    category: 'Kategorya',
    subject: 'Paksa',
    referral: 'Komiteng pinagsangguni',
    classification: 'Klasipikasyon',
    actionTaken: 'Aksyong ginawa',
    author: 'May-akda',
    coAuthor: 'Kapwa may-akda',
  },
  orderOfBusiness: 'Kaayusan ng Gawain',
  printAgenda: 'I-print ang agenda',

  requestText: 'Humiling ng sertipikadong kopya ng rekord pambatasan mula sa Tanggapan ng Kalihim ng Sanggunian.',
  requestRecordPlaceholder: 'Numero o pamagat ng rekord (hal. Mun. Ord. No. 2026-005)',
  requestRecordLabel: 'Dokumentong hinihiling',
  purpose: 'Layunin',
  purposes: {
    'Personal reference': 'Personal na sanggunian',
    'Research / Academic': 'Pananaliksik / Akademiko',
    'Legal proceedings': 'Legal na paglilitis',
    'Business compliance': 'Pagsunod ng negosyo',
    Other: 'Iba pa',
  },
  consentBefore: 'Sa pagpapasa, sumasang-ayon ka sa pagproseso ng iyong personal na datos ayon sa',
  submitRequest: 'Ipasa ang kahilingan',
  requestReceivedTitle: 'Natanggap ang kahilingan',
  requestReceivedText: (reference: string, email: string) =>
    `Ang iyong reference number ay ${reference}. Magpapadala ng kumpirmasyon sa ${email}. Ipakita ang reference number na ito sa pagkuha ng dokumento sa Tanggapan ng SB.`,
  done: 'Tapos na',
  cancel: 'Kanselahin',

  needNameEmail: 'Pakilagay ang iyong buong pangalan at email address.',
  invalidEmail: 'Pakilagay ang wastong email address.',
  notValidEmail: (email: string) => `Hindi wastong email address ang ${email}.`,
  registrationNotSaved: 'Hindi naisave ang rehistro',
  confirmRegistrationTitle: 'Ipasa ang iyong rehistro?',
  confirmRegistrationSubscribed: (name: string, email: string) => `Irerehistro si ${name} gamit ang ${email} at isu-subscribe sa mga update sa lehislasyon.`,
  confirmRegistration: (name: string, email: string) => `Irerehistro si ${name} gamit ang ${email}.`,
  registrationSaved: 'Naisave ang rehistro',
  registrationSubscribed: 'Naisave ang rehistro. Naka-subscribe ka na sa mga update sa lehislasyon.',
  registrationNoUpdates: 'Naisave ang rehistro. Maaari mong i-on ang mga update anumang oras.',
  enterReference: 'Pakilagay ang reference number.',
  lookupFailed: 'Hindi nahanap',
  accFound: 'Natagpuan ang akreditasyon',
  accNotFoundTitle: 'Walang natagpuang akreditasyon',
  accNotFound: (key: string) => `Walang kahilingan sa akreditasyon para sa ${key}.`,
  requestIncomplete: 'Pakikumpleto ang iyong pangalan, email address, at ang dokumentong hinihiling.',
  requestNotSubmitted: 'Hindi naipasa ang kahilingan',
  confirmRequestTitle: 'Ipasa ang kahilingang ito?',
  confirmRequest: (record: string, email: string) => `Ipapadala sa SB Secretariat ang kahilingan para sa "${record}". Ang mga update ay ipapadala sa ${email}.`,
  requestSubmitted: 'Naipasa ang kahilingan',
  yourReference: (reference: string) => `Ang iyong reference number ay ${reference}.`,
  inquiryIncomplete: 'Pakikumpleto ang iyong pangalan, email address, at mensahe.',
  inquiryNotSent: 'Hindi naipadala ang katanungan',
  confirmInquiryTitle: 'Ipadala ang katanungang ito?',
  confirmInquiry: (email: string) => `Ipapadala sa SB Secretariat ang iyong katanungan. Ang sagot ay ipapadala sa ${email}.`,
  inquirySent: 'Naipadala ang katanungan',

  policies: {
    privacy: [
      'Kinokolekta lamang ng LIMS ang personal na impormasyong kailangan upang maproseso ang mga pampublikong rehistro, katanungan, at paghiling ng dokumento, alinsunod sa Data Privacy Act of 2012 (RA 10173).',
      'Ginagamit lamang ang impormasyon para sa nakasaad na layunin, itinatago lamang hangga’t kailangan, at pinoprotektahan laban sa hindi awtorisadong pag-access. Maaari kang humiling ng access, pagtatama, o pagbura ng iyong datos sa Tanggapan ng Kalihim ng Sanggunian sa {email}.',
    ],
    terms: [
      'Ang mga dokumento sa portal na ito ay para sa pampublikong kaalaman. Ang mga na-download at na-print na kopya ay may markang “Public Copy” at hindi sertipikadong tunay na kopya. Maaaring humiling ng sertipikadong kopya sa Tanggapan ng Kalihim ng Sanggunian.',
    ],
    accessibility: [
      'Ang portal na ito ay dinisenyo para gumana sa telepono, tablet, at computer, sumusuporta sa keyboard navigation, at gumagamit ng malinaw na teksto at kulay. Iulat ang mga problema sa accessibility sa {email}.',
    ],
  },
};

export const LANDING_COPY: Record<Lang, LandingCopy> = { EN, FIL };
